# ChatData

## Sqlite
We are using a file system called **sqlite**. It looks and acts like a real single user relational database (RDB). sqlite3 comes packaged with python. You do not need to install the library. You simply import it (as below).

- We are using Pandas to write and read to sqlite. Pandas will manage a lot of the complexity of dealing with a RDB. There are other ways of reading and writing to a RDB that are VERY common and often used in production systems.  

- The most common other way is to read or write to the RDB row by row. As you can see Pandas puts the entire dataframe into the RDB or extracts a new dataframe from the RDB. These are not row by row operations. These are set operations. Set operations ARE more efficient. However, it is common to use row by row operations to avoid needing large memory computers to hold the dataframes. One row only takes a few bytes. An entire dataframe could be many gigabytes and even petabytes of data. Obviously you will end up with problems with your compute resource if your files are this big. This will not happen to you in this activity and may never happen to you while you are a data analyst. Please just be aware of this.

- This activity is primarily about querying a RDB, so, we are using a simple way that Pandas provides. If you want to learn the more complex way, just google 'reading and wrting to a relational database using python'. There are many resources to learn from.

- The data types that sqlite supports are quite limited. for example, it does not have a DATE type.  This is not a challenge for this project. However, more sophisticated database systems,such as Postgresql, have a large array of data types, such as "DATE", etc. that give those systems additional capability.

- All of the SQL queries could also be performed on the Pandas DataFrames directly.  You may want to try this yourself for comparison (but make sure you do the SQL queries first, as this is an exercise in using SQL!).


## SQL Magic
Within the Jupyter notebook we will be using something called **SQL Magic**.  This provides a convenient way to write SQL queries directly into code cells in the notebook and to read the results back into a Pandas DataFrame.  This makes working with SQL much easier!

Note that you may need to update your sqlite version using `conda update -c anaconda sqlite` in order for the SQL Magic to work correctly.

## The Data Analysis Lifecycle
The sections in this notebook follow the stages of the Data Analysis Lifecycle introduced in an earlier activity.  The stages are:

- Acquire
- Transform
- Organise
- Analyse
- Communicate
- Maintain

The requirements document for this project is Template SQL queries.xlsx.

# Preliminary Steps: Create a Database
First let's import Sqlite and the other libraries we will need.

In [87]:
# Import Libraries
import numpy as np
import pandas as pd
import sqlite3

### Create the Database
Now we will create the Sqlite database.  Here is some code that does this for you.  We use the `%load_ext` magic command to load the SQL Magic extension and then use `%sql` to connect to the database.

In [88]:
# If the db does not exist, sqlite will create it.
con = sqlite3.connect('chatdata.db')

# loads sql magic
%load_ext sql

# connects sql magic command to the correct db
%sql sqlite:///chatdata.db

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

#### Drop the `queries` table if it already exists
The queries table will be our record of the queries created to answer the questions from the requirements spreadsheet.  As we will be running this Jupyter notebook a few times, let's drop (i.e. remove) the queries table so that we start fresh each time.  Here is the code to do this.  We use the `%%sql` magic command to tell Jupyter that we are going to write SQL in the cell.

In [89]:
%%sql
DROP TABLE IF EXISTS 'queries'

 * sqlite:///chatdata.db
Done.

[]

# Task 1: Load the Data
Now we can start loading the data.  The tables will be created as we load the data.  

Note that some of these files are quite large, so make sure you have plenty of free memory!

## Lifecycle Stages: Transform and Organise
The data has already been processed into 3 clean data files ready for this project:

- queries.csv
- posts.csv
- comments.csv

We will load these files into our database.

## Lifecycle Stage: Acquire
The data can be found in the OpenClassrooms instructions for this activity.

### Load Comments Data into a `comments` table
Now we will load the data from the csv files into our sqlite database.

First we load the csv file into a Pandas dataframe:

In [90]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [91]:
comments = pd.read_csv('/content/drive/MyDrive/comments.csv')
comments.head()

,Id,PostId,Score,Text,CreationDate,UserId
0,723182,385124,0,@BenBolker I don't understand. The fit cannot ...,01/01/2019 00:06,78575
1,723183,385124,3,"You can't add *less* than (`-min(y)`), but you...",01/01/2019 00:09,2126
2,723186,385137,0,nice. If you felt like doing the work it would...,01/01/2019 00:32,2126
3,723187,385137,0,"i.e. `emdbook::curve3d(-sum(dnbinom(y,mu=mu,si...",01/01/2019 00:40,2126
4,723188,385134,0,"Don't you mean ""so variance should be $\sigma^...",01/01/2019 00:41,112141

Now take the comments dataframe and push the data into the Sqlite database table called 'comments':

In [92]:
# load comments into sqlite
comments.to_sql('comments', con, if_exists='replace', index=False)

# read back in to prove that it worked
sql = 'SELECT * FROM comments'
comments = pd.read_sql(sql, con)
comments.head()

,Id,PostId,Score,Text,CreationDate,UserId
0,723182,385124,0,@BenBolker I don't understand. The fit cannot ...,01/01/2019 00:06,78575
1,723183,385124,3,"You can't add *less* than (`-min(y)`), but you...",01/01/2019 00:09,2126
2,723186,385137,0,nice. If you felt like doing the work it would...,01/01/2019 00:32,2126
3,723187,385137,0,"i.e. `emdbook::curve3d(-sum(dnbinom(y,mu=mu,si...",01/01/2019 00:40,2126
4,723188,385134,0,"Don't you mean ""so variance should be $\sigma^...",01/01/2019 00:41,112141

### Load Other CSVs
Now that you have seen the code for loading in the comments.csv now do the same to read and write the posts.csv and users.csv to sqlite.

<div style="background-color:lemonchiffon; border:1px solid; padding:5px; margin:5px; font-weight:bold"><font color="crimson">
TODO: Enter code in the following cells. Insert as many cells as you want to do this.
    </font></div>

In [93]:
users = pd.read_csv('/content/drive/MyDrive/users.csv')
users.head()

,Id,Reputation,CreationDate,DisplayName,LastAccessDate,WebsiteUrl,Location,AboutMe,Views,UpVotes,DownVotes,ProfileImageUrl,AccountId
0,157607,31,2017-04-17 14:50:42,user157607,2019-07-23 16:44:08,NaN,NaN,NaN,0,0,0,https://www.gravatar.com/avatar/2efb161849efa4...,10705183
1,157656,101,2017-04-17 20:08:20,user102859,2019-06-26 13:42:13,NaN,NaN,NaN,3,0,0,https://i.stack.imgur.com/eY4ka.jpg?s=128&g=1,10567606
2,157704,133,2017-04-18 05:10:47,jupiar,2019-11-25 13:32:27,NaN,"Shanghai, China","<p>Originally from the U.K, I have an Undergra...",1,1,0,https://www.gravatar.com/avatar/720e20205122c5...,9501631
3,157709,155,2017-04-18 06:39:18,farmer,2019-02-17 19:44:24,NaN,NaN,NaN,16,0,0,https://www.gravatar.com/avatar/0f8c4bde3d8f25...,10709837
4,157755,101,2017-04-18 12:56:17,Miki P,2019-08-12 17:02:21,NaN,NaN,NaN,1,9,0,https://www.gravatar.com/avatar/af088558cd81c5...,7969290

In [94]:
users.to_sql('users', con, if_exists='replace', index=False)

# read back in to prove that it worked
sql = 'SELECT * FROM users'
users = pd.read_sql(sql, con)
users.head()

,Id,Reputation,CreationDate,DisplayName,LastAccessDate,WebsiteUrl,Location,AboutMe,Views,UpVotes,DownVotes,ProfileImageUrl,AccountId
0,157607,31,2017-04-17 14:50:42,user157607,2019-07-23 16:44:08,None,None,None,0,0,0,https://www.gravatar.com/avatar/2efb161849efa4...,10705183
1,157656,101,2017-04-17 20:08:20,user102859,2019-06-26 13:42:13,None,None,None,3,0,0,https://i.stack.imgur.com/eY4ka.jpg?s=128&g=1,10567606
2,157704,133,2017-04-18 05:10:47,jupiar,2019-11-25 13:32:27,None,"Shanghai, China","<p>Originally from the U.K, I have an Undergra...",1,1,0,https://www.gravatar.com/avatar/720e20205122c5...,9501631
3,157709,155,2017-04-18 06:39:18,farmer,2019-02-17 19:44:24,None,None,None,16,0,0,https://www.gravatar.com/avatar/0f8c4bde3d8f25...,10709837
4,157755,101,2017-04-18 12:56:17,Miki P,2019-08-12 17:02:21,None,None,None,1,9,0,https://www.gravatar.com/avatar/af088558cd81c5...,7969290

In [95]:
posts = pd.read_csv('/content/drive/MyDrive/posts.csv')
posts.head()

,Id,PostTypeId,AcceptedAnswerId,ParentId,CreationDate,Score,ViewCount,Body,OwnerUserId,OwnerDisplayName,...,LastEditorDisplayName,LastEditDate,LastActivityDate,Title,Tags,AnswerCount,CommentCount,FavoriteCount,ClosedDate,CommunityOwnedDate
0,423497,1,423511,0,2019-08-24 09:39:31,2,68,"<p>From wikipedia <a href=""https://en.wikipedi...",64552,NaN,...,NaN,NaN,2019-08-24 11:38:54,When are biased estimators with lower MSE pref...,<bias><unbiased-estimator><mse>,1,0,1,2019-08-25 10:25:24,NaN
1,423498,1,0,0,2019-08-24 09:47:42,1,24,<p>I am currently doing local sensitivity anal...,87231,NaN,...,NaN,2019-09-06 12:52:32,2019-09-06 12:52:32,How to interpret the result from local sensiti...,<sensitivity-analysis><elasticity>,1,0,0,NaN,NaN
2,423499,1,0,0,2019-08-24 09:48:26,1,56,<p>I'm an honours student in psychology doing ...,257207,NaN,...,NaN,NaN,2019-08-25 08:54:17,Power Analysis in G-Power - Mixed Model Anova,<anova><gpower>,2,0,0,NaN,NaN
3,423500,2,0,215865,2019-08-24 09:57:01,0,0,"<p>Maybe you can look this <a href=""https://me...",106606,NaN,...,NaN,NaN,2019-08-24 09:57:01,NaN,NaN,0,0,0,NaN,NaN
4,423502,2,0,423286,2019-08-24 10:44:52,3,0,<blockquote>\n <p>Q1) Is my approach valid?</...,220643,NaN,...,NaN,2019-08-24 12:13:46,2019-08-24 12:13:46,NaN,NaN,0,1,0,NaN,NaN

In [96]:
posts.to_sql('posts', con, if_exists='replace', index=False)

# read back in to prove that it worked
sql = 'SELECT * FROM posts'
posts = pd.read_sql(sql, con)
posts.head()

,Id,PostTypeId,AcceptedAnswerId,ParentId,CreationDate,Score,ViewCount,Body,OwnerUserId,OwnerDisplayName,...,LastEditorDisplayName,LastEditDate,LastActivityDate,Title,Tags,AnswerCount,CommentCount,FavoriteCount,ClosedDate,CommunityOwnedDate
0,423497,1,423511,0,2019-08-24 09:39:31,2,68,"<p>From wikipedia <a href=""https://en.wikipedi...",64552,None,...,None,None,2019-08-24 11:38:54,When are biased estimators with lower MSE pref...,<bias><unbiased-estimator><mse>,1,0,1,2019-08-25 10:25:24,None
1,423498,1,0,0,2019-08-24 09:47:42,1,24,<p>I am currently doing local sensitivity anal...,87231,None,...,None,2019-09-06 12:52:32,2019-09-06 12:52:32,How to interpret the result from local sensiti...,<sensitivity-analysis><elasticity>,1,0,0,None,None
2,423499,1,0,0,2019-08-24 09:48:26,1,56,<p>I'm an honours student in psychology doing ...,257207,None,...,None,None,2019-08-25 08:54:17,Power Analysis in G-Power - Mixed Model Anova,<anova><gpower>,2,0,0,None,None
3,423500,2,0,215865,2019-08-24 09:57:01,0,0,"<p>Maybe you can look this <a href=""https://me...",106606,None,...,None,None,2019-08-24 09:57:01,None,None,0,0,0,None,None
4,423502,2,0,423286,2019-08-24 10:44:52,3,0,<blockquote>\n <p>Q1) Is my approach valid?</...,220643,None,...,None,2019-08-24 12:13:46,2019-08-24 12:13:46,None,None,0,1,0,None,None

### **TODO**: Drop Duplicates
Look for and drop any duplicates in all 3 of the tables (if they exist). Use Pandas to do this. If you find duplicates, you will need to rewrite the table.

<div style="background-color:lemonchiffon; border:1px solid; padding:5px; margin:5px; font-weight:bold"><font color="crimson">
TODO: Enter code in the following cells.
    </font></div>

In [97]:
id_count = comments ['Id'].value_counts()
id_count

723182    1
769788    1
768879    1
768880    1
768881    1
         ..
746468    1
746469    1
746470    1
746472    1
791753    1
Name: Id, Length: 50000, dtype: int64

In [98]:
id_count = users ['Id'].value_counts()
id_count

157607    1
35998     1
182632    1
182594    1
182590    1
         ..
243754    1
243759    1
243763    1
243765    1
157592    1
Name: Id, Length: 18412, dtype: int64

In [99]:
id_count = posts ['Id'].value_counts()
id_count

423497    1
420405    1
420409    1
420410    1
420412    1
         ..
402692    1
402693    1
402694    1
402695    1
438743    1
Name: Id, Length: 42234, dtype: int64

## Review the Data

Spend some time reviewing the data.  Understand what data we have, think about how that data can be used to assist in the initiative of understanding how ChatData is used in the real world.  Is the data organised in a way that would lend itself to being manged in a relational database?  How would the different tables be connected?  What are the primary and foreign keys?  Would this give you a 3NF model?

Also think about security and ethics.  Is there personal data in here?  Could individuals be identified through this data?  It it ethical to use the data in this way?  You will be asked to comment on these questions later!

Use the code below to help you.

In [100]:
users.columns

Index(['Id', 'Reputation', 'CreationDate', 'DisplayName', 'LastAccessDate',
       'WebsiteUrl', 'Location', 'AboutMe', 'Views', 'UpVotes', 'DownVotes',
       'ProfileImageUrl', 'AccountId'],
      dtype='object')

In [101]:
users.head()

,Id,Reputation,CreationDate,DisplayName,LastAccessDate,WebsiteUrl,Location,AboutMe,Views,UpVotes,DownVotes,ProfileImageUrl,AccountId
0,157607,31,2017-04-17 14:50:42,user157607,2019-07-23 16:44:08,None,None,None,0,0,0,https://www.gravatar.com/avatar/2efb161849efa4...,10705183
1,157656,101,2017-04-17 20:08:20,user102859,2019-06-26 13:42:13,None,None,None,3,0,0,https://i.stack.imgur.com/eY4ka.jpg?s=128&g=1,10567606
2,157704,133,2017-04-18 05:10:47,jupiar,2019-11-25 13:32:27,None,"Shanghai, China","<p>Originally from the U.K, I have an Undergra...",1,1,0,https://www.gravatar.com/avatar/720e20205122c5...,9501631
3,157709,155,2017-04-18 06:39:18,farmer,2019-02-17 19:44:24,None,None,None,16,0,0,https://www.gravatar.com/avatar/0f8c4bde3d8f25...,10709837
4,157755,101,2017-04-18 12:56:17,Miki P,2019-08-12 17:02:21,None,None,None,1,9,0,https://www.gravatar.com/avatar/af088558cd81c5...,7969290

In [102]:
comments.columns

Index(['Id', 'PostId', 'Score', 'Text', 'CreationDate', 'UserId'], dtype='object')

In [103]:
comments.head()

,Id,PostId,Score,Text,CreationDate,UserId
0,723182,385124,0,@BenBolker I don't understand. The fit cannot ...,01/01/2019 00:06,78575
1,723183,385124,3,"You can't add *less* than (`-min(y)`), but you...",01/01/2019 00:09,2126
2,723186,385137,0,nice. If you felt like doing the work it would...,01/01/2019 00:32,2126
3,723187,385137,0,"i.e. `emdbook::curve3d(-sum(dnbinom(y,mu=mu,si...",01/01/2019 00:40,2126
4,723188,385134,0,"Don't you mean ""so variance should be $\sigma^...",01/01/2019 00:41,112141

In [104]:
posts.columns

Index(['Id', 'PostTypeId', 'AcceptedAnswerId', 'ParentId', 'CreationDate',
       'Score', 'ViewCount', 'Body', 'OwnerUserId', 'OwnerDisplayName',
       'LastEditorUserId', 'LastEditorDisplayName', 'LastEditDate',
       'LastActivityDate', 'Title', 'Tags', 'AnswerCount', 'CommentCount',
       'FavoriteCount', 'ClosedDate', 'CommunityOwnedDate'],
      dtype='object')

In [105]:
posts.head()

,Id,PostTypeId,AcceptedAnswerId,ParentId,CreationDate,Score,ViewCount,Body,OwnerUserId,OwnerDisplayName,...,LastEditorDisplayName,LastEditDate,LastActivityDate,Title,Tags,AnswerCount,CommentCount,FavoriteCount,ClosedDate,CommunityOwnedDate
0,423497,1,423511,0,2019-08-24 09:39:31,2,68,"<p>From wikipedia <a href=""https://en.wikipedi...",64552,None,...,None,None,2019-08-24 11:38:54,When are biased estimators with lower MSE pref...,<bias><unbiased-estimator><mse>,1,0,1,2019-08-25 10:25:24,None
1,423498,1,0,0,2019-08-24 09:47:42,1,24,<p>I am currently doing local sensitivity anal...,87231,None,...,None,2019-09-06 12:52:32,2019-09-06 12:52:32,How to interpret the result from local sensiti...,<sensitivity-analysis><elasticity>,1,0,0,None,None
2,423499,1,0,0,2019-08-24 09:48:26,1,56,<p>I'm an honours student in psychology doing ...,257207,None,...,None,None,2019-08-25 08:54:17,Power Analysis in G-Power - Mixed Model Anova,<anova><gpower>,2,0,0,None,None
3,423500,2,0,215865,2019-08-24 09:57:01,0,0,"<p>Maybe you can look this <a href=""https://me...",106606,None,...,None,None,2019-08-24 09:57:01,None,None,0,0,0,None,None
4,423502,2,0,423286,2019-08-24 10:44:52,3,0,<blockquote>\n <p>Q1) Is my approach valid?</...,220643,None,...,None,2019-08-24 12:13:46,2019-08-24 12:13:46,None,None,0,1,0,None,None

# Working with Sqlite and SQL Magic
In this section let's spend a little time understanding a bit more about how we can work with Sqlite within Jupyter.

Let's look at 2 ways to query the sqlite database: using SQL Magic or using Pandas.  Either way is fine for this project.

## Writing queries with SQL Magic

You will now need to write some queries to get answers to the questions in the requirements.  

For single-line queries, start the cell with `%sql` and simply enter your query:

In [106]:
# This is an example
%sql SELECT COUNT(*) FROM comments

 * sqlite:///chatdata.db
Done.

[(50000,)]

For multi line sql statements use `%%sql` as follows. This tells Jupyter that *everything* in this cell should be interpreted as sql. So, NO comments other statements are allowed:

In [107]:
%%sql
SELECT Id, PostId, Score, Text
    FROM comments
        LIMIT 5

 * sqlite:///chatdata.db
Done.

[(723182, 385124, 0, '@BenBolker I don\'t understand. The fit cannot be done for the negative $y$. So intuitively I\'d think that in order to retain the relativity of the  ... (24 characters truncated) ... rror" or "flip" it to the positive axis? Would it be possible to adjust every point individually? Basically e.g. take $abs(y_i)$ instead of minimums.'),
 (723183, 385124, 3, "You can't add *less* than (`-min(y)`), but you could add *more*. I'm going to stop answering now sorry, because **judging what the 'best' approach is ... (60 characters truncated) ...  of the analysis, why you need to fit an exponential, your level of computational and statistical sophistication and that of your audience, etc. ...)"),
 (723186, 385137, 0, 'nice. If you felt like doing the work it would be nice to generate an image/contour plot of log-likelihood as a function of (mu, theta) and show the lines corresponding to the two `size` values .'),
 (723187, 385137, 0, 'i.e. `emdbook::curve3d(-sum(dnbinom(y,mu=mu,size=size,log=TRUE)),\n                 xlim=c(2,5),ylim=c(0.2,0.5),\n                 varnames=c("mu","s ... (57 characters truncated) ... ,col="red")\nabline(h=fit.what$theta,col="blue")\n` ... although doesn\'t look this is actually the answer - mu-hat is independent of theta-hat ... ?'),
 (723188, 385134, 0, 'Don\'t you mean "so variance should be $\\sigma^2/(n\\mu^2)$"')]

## Writing queries with Pandas
Another way to write queries is to use pandas:

In [108]:
sql = """
SELECT Id, PostId, Score, Text
    FROM comments
        LIMIT 5
        """
result = pd.read_sql(sql, con)
result

       Id  PostId  Score                                               Text
0  723182  385124      0  @BenBolker I don't understand. The fit cannot ...
1  723183  385124      3  You can't add *less* than (`-min(y)`), but you...
2  723186  385137      0  nice. If you felt like doing the work it would...
3  723187  385137      0  i.e. `emdbook::curve3d(-sum(dnbinom(y,mu=mu,si...
4  723188  385134      0  Don't you mean "so variance should be $\sigma^...

# Creating Tables with Referential Integrity

When we loaded the csv files into Sqlite database tables, Sqlite created the tables for us behind the scenes. Let's inspect this a bit more.

We can see how Sqlite created the tables by querying the `sqlite_master` table, which Sqlite uses to keep track of what objects have been created in the database:

In [109]:
%%sql
select sql from sqlite_master

 * sqlite:///chatdata.db
Done.

[('CREATE TABLE "comments" (\n"Id" INTEGER,\n  "PostId" INTEGER,\n  "Score" INTEGER,\n  "Text" TEXT,\n  "CreationDate" TEXT,\n  "UserId" INTEGER\n)',),
 ('CREATE TABLE "users" (\n"Id" INTEGER,\n  "Reputation" INTEGER,\n  "CreationDate" TEXT,\n  "DisplayName" TEXT,\n  "LastAccessDate" TEXT,\n  "WebsiteUr ... (17 characters truncated) ... tion" TEXT,\n  "AboutMe" TEXT,\n  "Views" INTEGER,\n  "UpVotes" INTEGER,\n  "DownVotes" INTEGER,\n  "ProfileImageUrl" TEXT,\n  "AccountId" INTEGER\n)',),
 ('CREATE TABLE "posts" (\n"Id" INTEGER,\n  "PostTypeId" INTEGER,\n  "AcceptedAnswerId" INTEGER,\n  "ParentId" INTEGER,\n  "CreationDate" TEXT,\n  "Scor ... (240 characters truncated) ...   "Tags" TEXT,\n  "AnswerCount" INTEGER,\n  "CommentCount" INTEGER,\n  "FavoriteCount" INTEGER,\n  "ClosedDate" TEXT,\n  "CommunityOwnedDate" TEXT\n)',)]

The above results show the `CREATE TABLE` statements that could be used by Sqlite to recreate the tables with the exact same structure.

The problem with the CREATE TABLE statements above is that they don't enforce **referential integrity**.  In other words, they don't ensure that every UserId and PostId in the comments table refers to an actual UserId and PostId in the users and posts tables.  At the moment. we can insert any old number here, and even have multiple users with the same Id!  One of the advantages of working with relational databases is that they can enforce the correct uniqueness and relationships in the data, but at the moment we are not using that feature.  So let's fix that...

First, let's drop the original tables:

In [110]:
%%sql
DROP TABLE comments;
DROP TABLE users;
DROP TABLE posts;

 * sqlite:///chatdata.db
Done.
Done.
Done.

[]

Prove that this worked by selecting the names of the tables back.  We should have no tables:

In [111]:
%%sql
SELECT name FROM sqlite_master WHERE type='table'
    ORDER BY name

 * sqlite:///chatdata.db
Done.

[]

In Sqlite we need to enable the enforcement of foreign key constraints:

In [112]:
%%sql
PRAGMA foreign_keys=ON;

 * sqlite:///chatdata.db
Done.

[]

Now recreate the users table with a **primary key constraint** by copying the CREATE TABLE statement from above and adding the NOT NULL PRIMARY KEY clause to the Id:

In [113]:
%%sql
CREATE TABLE "users" (
"Id" INTEGER NOT NULL PRIMARY KEY,
"Reputation" INTEGER,
"CreationDate" TEXT,
"DisplayName" TEXT,
"LastAccessDate" TEXT,
"WebsiteUrl" TEXT,
"Location" TEXT,
"AboutMe" TEXT,
"Views" INTEGER,
"UpVotes" INTEGER,
"DownVotes" INTEGER,
"ProfileImageUrl" TEXT,
"AccountId" INTEGER
);

 * sqlite:///chatdata.db
Done.

[]

Now do the same for the posts table:

<div style="background-color:lemonchiffon; border:1px solid; padding:5px; margin:5px; font-weight:bold"><font color="crimson">
TODO: Complete the following code cell
    </font></div>

In [114]:
# Run the CREATE TABLE statement for the posts table, including the primary key constraint
%%sql
CREATE TABLE IF NOT EXISTS"posts" (
    "Id" INTEGER NOT NULL PRIMARY KEY,
    "PostTypeId" INTEGER,
    "AcceptedAnswerId" INTEGER,
    "ParentId" INTEGER,
    "CreationDate" TEXT,
    "Score" INTEGER,
    "ViewCount" INTEGER,
    "Body" TEXT,
    "OwnerUserId" INTEGER,
    "OwnerDisplayName" TEXT,
    "LastEditorUserId" INTEGER,
    "LastEditorDisplayName" TEXT,
    "LastEditDate" TEXT,
    "LastActivityDate" TEXT,
    "Title" TEXT,
    "Tags" TEXT,
    "AnswerCount" INTEGER,
    "CommentCount" INTEGER,
    "FavoriteCount" INTEGER,
    "ClosedDate" TEXT,
    "CommunityOwnedDate" TEXT
);

 * sqlite:///chatdata.db
Done.

[]

Now for the comments table.  We need to add the primary key constraint on the id here as we did for users and posts, but we also need to add FOREIGN KEY constraints on the UserId and PostId. Read the documentation here and find our how to do that: https://www.sqlite.org/foreignkeys.html.  Then create the comments table with the correct constraints:

<div style="background-color:lemonchiffon; border:1px solid; padding:5px; margin:5px; font-weight:bold"><font color="crimson">
TODO: Complete the following code cell
    </font></div>

In [115]:
# Run the CREATE TABLE statement for the comments table, including the primary key constraint and the 2 foreign key constraints
%%sql
CREATE TABLE IF NOT EXISTS "comments" (
    "Id" INTEGER NOT NULL PRIMARY KEY,
    "PostId" INTEGER,
    "Score" INTEGER,
    "Text" TEXT,
    "CreationDate" TEXT,
    "UserId" INTEGER,
    FOREIGN KEY ("PostId") REFERENCES "posts" ("Id"),
    FOREIGN KEY ("UserId") REFERENCES "users" ("Id")
);

 * sqlite:///chatdata.db
Done.

[]

Now we can re-insert the data into these constrained tables.  First users:

In [116]:
# Insert data into the new users table
users.to_sql('users', con, if_exists='append', index=False)

18412

Now posts:

<div style="background-color:lemonchiffon; border:1px solid; padding:5px; margin:5px; font-weight:bold"><font color="crimson">
TODO: Complete the following code cell
    </font></div>

In [117]:
# Insert data into the new posts table
posts.to_sql('posts', con, if_exists='append', index=False)

42234

Finally comments, which references the users and posts tables:

<div style="background-color:lemonchiffon; border:1px solid; padding:5px; margin:5px; font-weight:bold"><font color="crimson">
TODO: Complete the following code cell
    </font></div>

In [118]:
# Insert data into the new comments table
comments.to_sql('comments', con, if_exists='append', index=False)

50000

Now check that we have the 3 new table definitions in Sqlite:

In [119]:
%%sql
SELECT name FROM sqlite_master WHERE type='table'
    ORDER BY name

 * sqlite:///chatdata.db
Done.

[('comments',), ('posts',), ('users',)]

We now have all the data in tables in Sqlite and the tables will enforce the referential integrity.

# Example Query and Pattern for Tasks 2 and 3

As you work through the next tasks, you will need to:

1. Prepare the Sqlite query to answer the question
2. Test it
3. Insert it into the `queries` table, so we have a record of it for others.

This is the process that we want you to follow for this project while completing it.

Let's see an example of this by answering the following question:

**Which 5 users have viewed the most times and what is the sum of those views per user?**

## Prepare the Sqlite query

First, let's write the query:

In [120]:
sql = """
SELECT Id, SUM(Views) AS TotalViews
    FROM Users
        GROUP BY Id
            ORDER BY TotalViews DESC
                LIMIT 5
                """
result = pd.read_sql(sql, con) # con is the connection to the database
result

     Id  TotalViews
0   919       85180
1  4253       35119
2   805       34637
3  7290       32639
4  3277       29255

## Test the query
You can optionally prove the query worked by performing the same query in Pandas:

In [121]:
results = users.groupby(['Id']).sum().sort_values('Views', ascending = False)[:5]
results['Views']

<ipython-input-121-7b2c47bab8fa>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  results = users.groupby(['Id']).sum().sort_values('Views', ascending = False)[:5]

Id
919     85180
4253    35119
805     34637
7290    32639
3277    29255
Name: Views, dtype: int64

## Insert the query into the `queries` table
Now we need to put this query into the `queries` table in sqlite. Remember we want these queries to be accessible to everybody that should have access to them. We do not want people writing and rewriting the same queires over and over again. The easiest thing to do is create a dictionary with the values and insert these into the queries table.  Note that the values are provided as lists as we are inserting a list of values (i.e. a number of rows) into the table.  In this case the number of rows is 1, so we have lists of 1 item.

So here, we have a column called 'task' with a list of values, a column called 'action' with a list of values, etc.

In [122]:
query_dict = {
              'task': ['Single Table Queries'],
              'action': ['Which 5 users have viewed the most times and what is the sum of those views per user?'],
              'query': [sql]
             }
query_dict

{'task': ['Single Table Queries'],
 'action': ['Which 5 users have viewed the most times and what is the sum of those views per user?'],
 'query': ['\nSELECT Id, SUM(Views) AS TotalViews\n    FROM Users\n        GROUP BY Id\n            ORDER BY TotalViews DESC\n                LIMIT 5\n                ']}

Now that you have the data structure (query_dict) containing the data, create a pandas dataframe that holds those values:

In [123]:
queries = pd.DataFrame(query_dict)
queries

,task,action,query
0,Single Table Queries,Which 5 users have viewed the most times and w...,"\nSELECT Id, SUM(Views) AS TotalViews\n FRO..."

Now load that pandas dataframe (queries) into the sqlite table called queries. In this case, you use append NOT replace. You will be adding to this tables as you go thru this project.

In [124]:
# load query into sqlite
queries.to_sql('queries', con, if_exists='append', index=False)

# read back in to prove that it worked
sql = 'SELECT * FROM queries'
queries = pd.read_sql(sql, con)
queries.head()

,task,action,query
0,Single Table Queries,Which 5 users have viewed the most times and w...,"\nSELECT Id, SUM(Views) AS TotalViews\n FRO..."

It is likely that as you iterate thru this notebook you will create some duplicate entries in the query table. Not a big deal. Just tell sql or pandas (much easier in pandas) to drop the duplicates! If you drop the duplicates in Pandas you will have to write the entire dataframe back to sqlite. Otherwise it is changed in memory in Pandas but NOT in sqlite on the disk drive (or SDD). Just do this drop at the end of this notebook so that you are not constantly dealing with this.

So, to summarise, as you go through the following tasks you need to:

- answer the question in sql
- prove it in pandas (if you want to)
- put the query into the queries table

# Task 1 (continued): Insert the CREATE TABLE Statements into the `queries` Table

Now that we understand how to populate the `queries` table, let's insert the CREATE TABLE statements into it.  First let's define a function to help us insert into the queries table:

In [125]:
# Define a function that will insert into the queries table
def store_query(task, action, query):
    query_dict = {
                  'task': [task],
                  'action': [action],
                  'query': [query]
                 }

    # put query into the query_dict
    queries = pd.DataFrame(query_dict)

    # load query into sqlite
    queries.to_sql('queries', con, if_exists='append', index=False)

Now we can specify the queries and call the above function to store them.  The first one is done for you.

In [126]:
sql = """
    CREATE TABLE "comments" (
    "Id" INTEGER,
    "PostId" INTEGER,
    "Score" INTEGER,
    "Text" TEXT,
    "CreationDate" TEXT,
    "UserId" INTEGER
    )
    """
store_query("Task 1", "Create table comments", sql)

Let's prove it works by selecting back from the queries table:

In [127]:
# Prove it works
%sql SELECT * FROM queries

 * sqlite:///chatdata.db
Done.

[('Single Table Queries', 'Which 5 users have viewed the most times and what is the sum of those views per user?', '\nSELECT Id, SUM(Views) AS TotalViews\n    FROM Users\n        GROUP BY Id\n            ORDER BY TotalViews DESC\n                LIMIT 5\n                '),
 ('Task 1', 'Create table comments', '\n    CREATE TABLE "comments" (\n    "Id" INTEGER,\n    "PostId" INTEGER,\n    "Score" INTEGER,\n    "Text" TEXT,\n    "CreationDate" TEXT,\n    "UserId" INTEGER\n    )\n    ')]

## Insert the other CREATE TABLE statements into the `queries` table.
Follow the above pattern to complete these code cells:

<div style="background-color:lemonchiffon; border:1px solid; padding:5px; margin:5px; font-weight:bold"><font color="crimson">
TODO: Complete the following code cells
    </font></div>

In [128]:
# Insert the CREATE TABLE for posts into the queries table
sql = """
    CREATE TABLE "posts" (
    "Id" INTEGER,
"PostTypeId" INTEGER,
"AcceptedAnswerId" INTEGER,
"ParentId" INTEGER,
"CreationDate" TEXT,
"Score" INTEGER,
"ViewCount" INTEGER,
"Body" TEXT,
"OwnerUserId" INTEGER,
"OwnerDisplayName" TEXT,
"LastEditorUserId" INTEGER,
"LastEditorDisplayName" TEXT,
"LastEditDate" TEXT,
"LastActivityDate" TEXT,
"Title" TEXT,
"Tags" TEXT,
"AnswerCount" INTEGER,
"CommentCount" INTEGER,
"FavoriteCount" INTEGER,
"ClosedDate" TEXT,
"CommunityOwnedDate" TEXT
)
    """
store_query("Task 1", "Create table posts", sql)

In [129]:
# Prove it works
%sql SELECT * FROM queries

 * sqlite:///chatdata.db
Done.

[('Single Table Queries', 'Which 5 users have viewed the most times and what is the sum of those views per user?', '\nSELECT Id, SUM(Views) AS TotalViews\n    FROM Users\n        GROUP BY Id\n            ORDER BY TotalViews DESC\n                LIMIT 5\n                '),
 ('Task 1', 'Create table comments', '\n    CREATE TABLE "comments" (\n    "Id" INTEGER,\n    "PostId" INTEGER,\n    "Score" INTEGER,\n    "Text" TEXT,\n    "CreationDate" TEXT,\n    "UserId" INTEGER\n    )\n    '),
 ('Task 1', 'Create table posts', '\n    CREATE TABLE "posts" (\n    "Id" INTEGER,\n"PostTypeId" INTEGER,\n"AcceptedAnswerId" INTEGER,\n"ParentId" INTEGER,\n"CreationDate" TEXT,\n"Scor ... (216 characters truncated) ... EXT,\n"Tags" TEXT,\n"AnswerCount" INTEGER,\n"CommentCount" INTEGER,\n"FavoriteCount" INTEGER,\n"ClosedDate" TEXT,\n"CommunityOwnedDate" TEXT\n)\n    ')]

In [130]:
# Insert the CREATE TABLE for users into the queries table
sql = """
CREATE TABLE "users" (
"Id" INTEGER,
"Reputation" INTEGER,
"CreationDate" TEXT,
"DisplayName" TEXT,
"LastAccessDate" TEXT,
"WebsiteUrl" TEXT,
"Location" TEXT,
"AboutMe" TEXT,
"Views" INTEGER,
"UpVotes" INTEGER,
"DownVotes" INTEGER,
"ProfileImageUrl" TEXT,
"AccountId" INTEGER
)
 """
store_query("Task 1", "Create table users", sql)

In [131]:
# Prove it works
%sql SELECT * FROM queries

 * sqlite:///chatdata.db
Done.

[('Single Table Queries', 'Which 5 users have viewed the most times and what is the sum of those views per user?', '\nSELECT Id, SUM(Views) AS TotalViews\n    FROM Users\n        GROUP BY Id\n            ORDER BY TotalViews DESC\n                LIMIT 5\n                '),
 ('Task 1', 'Create table comments', '\n    CREATE TABLE "comments" (\n    "Id" INTEGER,\n    "PostId" INTEGER,\n    "Score" INTEGER,\n    "Text" TEXT,\n    "CreationDate" TEXT,\n    "UserId" INTEGER\n    )\n    '),
 ('Task 1', 'Create table posts', '\n    CREATE TABLE "posts" (\n    "Id" INTEGER,\n"PostTypeId" INTEGER,\n"AcceptedAnswerId" INTEGER,\n"ParentId" INTEGER,\n"CreationDate" TEXT,\n"Scor ... (216 characters truncated) ... EXT,\n"Tags" TEXT,\n"AnswerCount" INTEGER,\n"CommentCount" INTEGER,\n"FavoriteCount" INTEGER,\n"ClosedDate" TEXT,\n"CommunityOwnedDate" TEXT\n)\n    '),
 ('Task 1', 'Create table users', '\nCREATE TABLE "users" (\n"Id" INTEGER,\n"Reputation" INTEGER,\n"CreationDate" TEXT,\n"DisplayName" TEXT,\n"LastAccessDate" TEXT,\n"WebsiteUrl" TEXT,\n"Location" TEXT,\n"AboutMe" TEXT,\n"Views" INTEGER,\n"UpVotes" INTEGER,\n"DownVotes" INTEGER,\n"ProfileImageUrl" TEXT,\n"AccountId" INTEGER\n)\n ')]

## Count the Number of Rows in Each Table
Run some queries to count the number of rows in each of the tables.  Don't forget to insert the query into the queries table.

<div style="background-color:lemonchiffon; border:1px solid; padding:5px; margin:5px; font-weight:bold"><font color="crimson">
TODO: Complete the following code cells
    </font></div>

In [132]:
# Count the number of rows in the comments table
%%sql
SELECT COUNT(*) AS NumberOfRows
FROM comments;

 * sqlite:///chatdata.db
Done.

[(50000,)]

In [133]:
# Count the number of rows in the users table
%%sql
SELECT COUNT(*) AS NumberOfRows
FROM users;

 * sqlite:///chatdata.db
Done.

[(18412,)]

In [134]:
# Count the number of rows in the posts table
%%sql
SELECT COUNT(*) AS NumberOfRows
FROM posts;

 * sqlite:///chatdata.db
Done.

[(42234,)]

## Do some Random Checks on the Data
Let's write some queries that select 5 random rows from each table.  The queries are provided here:

    select * from Comments order by random() limit 5;
    select * from Users order by random() limit 5;
    select * from Posts order by random() limit 5;

Enter the queries into the code cells below and insert the queries into the `queries` table in the same was as you did for the CREATE TABLE statements.

<div style="background-color:lemonchiffon; border:1px solid; padding:5px; margin:5px; font-weight:bold"><font color="crimson">
TODO: Complete the following code cells
    </font></div>

In [135]:
# Run the query to select 5 random rows from the posts table
%%sql
select *
from Posts
order by random() limit 5;

 * sqlite:///chatdata.db
Done.

[(409489, 2, 0, 405429, '2019-05-21 21:51:15', 0, 0, '<p>Assume <span class="math-container">$y = X\\beta + \\epsilon$</span> with <span class="math-container">$\\mathbb{E}[\\epsilon] = 0, Cov(\\epsilon) ... (739 characters truncated) ... p>\n\n<p>I hope to extend this to the case where <span class="math-container">$\\hat{\\sigma}$</span> is estimated from data some other time...</p>\n', 61496, None, 0, None, None, '2019-05-21 21:51:15', None, None, 0, 0, 0, None, None),
 (404602, 1, 405516, 0, '2019-04-23 13:29:50', 1, 463, '<p>I am new to Computer Vision. I am reading many papers and i see the term "pretext task". Can anyone explain what exactly it means.\nThanks in Advance.</p>\n', 219099, None, 0, None, None, '2019-04-28 18:10:55', 'Pretext Task in Computer Vision', '<machine-learning><computer-vision>', 2, 0, 0, None, None),
 (414062, 2, 0, 414010, '2019-06-21 05:37:58', 0, 0, '<p>Evaluation indexes could be considered their own clustering methods - just that there is no fast algorithm except trying all possible partitioning ... (687 characters truncated) ... nformation about what is "best",</strong> because each uses another definition of "best", and that may not be the one that you are looking for.</p>\n', 7828, None, 0, None, None, '2019-06-21 05:37:58', None, None, 0, 6, 0, None, None),
 (411180, 1, 0, 0, '2019-06-02 06:09:06', 0, 51, '<p>In SVM we have \n<span class="math-container">$$\\max_{\\alpha}1^T{\\alpha}-\\frac{1}{2}{\\alpha^T}Q{\\alpha}$$</span>\n<span class="math-containe ... (1149 characters truncated) ... g?\nIn svm it is so different form classic quadratic programming problem\nI don\'t know how to solve with the constraint because it has y value</p>\n', 249712, None, 128610, None, '2019-06-02 07:12:56', '2019-06-02 07:12:56', 'how to solve quadratic programming in SVM', '<svm>', 0, 0, 0, None, None),
 (433028, 1, 433030, 0, '2019-10-24 22:14:47', 4, 67, '<p>Given a pmf (probability mass function) for X (random variable): </p>\n\n\n\n<p><span class="math-container">\\begin{array}{|c|c|c|c|c|}\\hline x& ... (122 characters truncated) ... ld you know the cdf which is for values for <span class="math-container">$1 \\leq x &lt; 2$</span> since you do not know the values in between?</p>\n', 263667, None, 805, None, '2019-10-26 06:08:20', '2019-10-26 06:08:20', 'Given a pmf, how is it possible to calculate the cdf?', '<distributions><pdf><cdf><discrete-data>', 2, 2, 1, None, None)]

In [136]:
# Run the query to select 5 random rows from the posts comments
%%sql
select *
from Comments
order by random() limit 5;

 * sqlite:///chatdata.db
Done.

[(755210, 403772, 0, "So I would discard your first model, since it omits the main effect of Taxon. Just use Gavin's suggestion to get the main effects and interaction eff ... (22 characters truncated) ... emembering that smooths produced by the model are centered about 0 by default and need to be 'shifted' up or down depending on the intercept term(s).", '18/04/2019 13:32', 115634),
 (766711, 410554, 0, 'Thank You So Much for motivate me to understand but there is a 15 point reputation requirement for me to upvote, otherwise I will upvote your answer as well.', '29/05/2019 01:58', 13991),
 (731983, 389344, 1, "@CodeGuy [Austin](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3144483/) discusses pros and cons of regression adjustment versus propensity score met ... (285 characters truncated) ... o address your issue: taking observed groups that are unbalanced in covariates and matching or weighting cases to better approach a randomized study.", '29/01/2019 17:07', 28500),
 (773382, 413169, 0, "Could it be, for example, that whereas in X-variate mode it plots the components found using deflation for each succesive component (like in PCA), in XY-variate mode it's using the important components from the first mapping only?", '23/06/2019 21:35', 250623),
 (738911, 393292, 0, 'What do you mean "same information"? How do you define that? High correlation?', '21/02/2019 08:32', 143489)]

In [137]:
# Run the query to select 5 random rows from the users table
%%sql
select *
from Users
order by random() limit 5;

 * sqlite:///chatdata.db
Done.

[(11984, 2015, '2012-06-14 15:08:31', 'Alexey Zaytsev', '2019-11-27 18:23:26', 'http://scholar.google.com/citations?user=WfzzY4cAAAAJ', None, '<p>Researcher at Skoltech</p>\n\n<p>Data mining, machine learning and statistics</p>\n\n<p><a href="https://scholar.google.ru/citations?user=WfzzY4cAAAAJ&amp;hl=en" rel="nofollow noreferrer">https://scholar.google.ru/citations?user=WfzzY4cAAAAJ&amp;hl=en</a></p>\n', 261, 128, 1, None, 1568306),
 (222860, 103, '2018-10-07 19:44:13', 'user_6396', '2019-07-20 00:35:14', None, None, None, 0, 4, 0, 'https://www.gravatar.com/avatar/6130945ff1667b14dc3ca894685e46cf?s=128&d=identicon&r=PG&f=1', 13764581),
 (239828, 1, '2019-03-04 12:27:33', 'Nazlı Karamollaoğlu', '2019-06-26 06:18:09', None, None, None, 1, 0, 0, 'https://lh6.googleusercontent.com/-qzQXU9UVjQY/AAAAAAAAAAI/AAAAAAAABOA/kQdjsZEPmMo/photo.jpg', 15453389),
 (263082, 1, '2019-10-18 18:06:07', 'Richard Collins', '2019-10-18 21:47:50', None, None, None, 1, 0, 0, 'https://www.gravatar.com/avatar/490427fb305387dc0cc9cf60f5eaf6dc?s=128&d=identicon&r=PG&f=1', 16923932),
 (193164, 215, '2018-01-28 16:07:21', 'Legit Stack', '2019-05-24 21:33:08', 'http://maestroai.com/', 'Utah', None, 13, 4, 0, None, 3688520)]

# Task 2: Create Single Table Queries

## Lifecycle Stage: Analyze
We can now start the analysis with our single-table queries.  First we need to create a new computed column to help with one of the queries.  The code below creates a column called LEN_BODY which is the length of the BODY text:

In [138]:
%%sql
ALTER TABLE POSTS ADD COLUMN LEN_BODY INT

 * sqlite:///chatdata.db
Done.

[]

In [139]:
%%sql
UPDATE POSTS SET LEN_BODY = LENGTH(BODY)

 * sqlite:///chatdata.db
42234 rows affected.

[]

### Single Table Queries
From the Template SQL Queries there are a series of queries requested. You are responsible for coding the result. Use the pattern above to accomplish the coding objective.  Copy and paste the question (column B Action) into a markdown cell and answer the query. Use the pattern that you have been using above.

<div style="background-color:lemonchiffon; border:1px solid; padding:5px; margin:5px; font-weight:bold"><font color="crimson">
TODO: Enter your code below.  Just keep on inserting cells as you need them.
    </font></div>

In [140]:
%%sql
select *
from posts
Where LEN_BODY = 0;

 * sqlite:///chatdata.db
Done.

[]

In [141]:
# How many posts have 0 comments?
%%sql
SELECT COUNT(CommentCount), Id
FROM POSTS
WHERE CommentCount= 0;

 * sqlite:///chatdata.db
Done.

[(21713, 385136)]

In [142]:
# How many posts have 1 comments?
%%sql
SELECT Count(CommentCount)
FROM POSTS
WHERE CommentCount= 1;

 * sqlite:///chatdata.db
Done.

[(6460,)]

In [143]:
# How many posts have 2 comments or more?
%%sql
SELECT COUNT(CommentCount)
FROM POSTS
WHERE CommentCount = 2;

 * sqlite:///chatdata.db
Done.

[(4966,)]

In [144]:
# Find the 5 posts with the highest viewcount
%%sql
SELECT ViewCount, Id
FROM posts
ORDER BY viewcount DESC
LIMIT 5;

 * sqlite:///chatdata.db
Done.

[(19542, 388566),
 (16317, 394118),
 (11723, 431370),
 (9850, 398646),
 (6718, 434128)]

In [145]:
# Find the top 5 posts with the highest scores
%%sql
SELECT Score, Id
FROM posts
ORDER BY score DESC
LIMIT 5;

 * sqlite:///chatdata.db
Done.

[(101, 431397), (100, 394128), (93, 426878), (80, 388578), (77, 431370)]

In [146]:
# What are the 5 most frequent scores on posts?
%%sql
SELECT Score, COUNT(Score) AS Frequency, Id
FROM posts
GROUP BY Score
ORDER BY Frequency DESC, Score DESC
LIMIT 5;

 * sqlite:///chatdata.db
Done.

[(0, 19888, 385136),
 (1, 11867, 385137),
 (2, 5094, 385138),
 (3, 2228, 385148),
 (4, 1059, 385139)]

In [147]:
# How many posts have the keyword "data" in their tags?
%%sql
SELECT COUNT(*) AS NumberOfPosts, Id
FROM posts
WHERE tags LIKE '%data%';

 * sqlite:///chatdata.db
Done.

[(2242, 385143)]

In [148]:
# What are the 5 most frequent commentcount for posts?
%%sql
SELECT CommentCount, COUNT(*) AS Frequency, Id
FROM posts
GROUP BY CommentCount
ORDER BY Frequency DESC, CommentCount DESC
LIMIT 5;

 * sqlite:///chatdata.db
Done.

[(0, 21713, 385136),
 (1, 6460, 385145),
 (2, 4966, 385137),
 (3, 3063, 385144),
 (4, 2026, 385208)]

In [149]:
# How many posts have an accepted answer?
%%sql
SELECT count(posts.Id)
FROM posts
WHERE AcceptedAnswerId !=0;

 * sqlite:///chatdata.db
Done.

[(5341,)]

In [150]:
# What is the average reputation of table users?
%%sql
SELECT ROUND( AVG(reputation))
FROM users
where reputation!=0

 * sqlite:///chatdata.db
Done.

[(312.0,)]

In [151]:
# What are the min and max reputation of users?
%%sql
SELECT MIN(Reputation), MAX(Reputation)
FROM users;

 * sqlite:///chatdata.db
Done.

[(1, 228662)]

In [152]:
# What is the length of the body of 5 most viewed posts?
%%sql
SELECT LENGTH(Body) AS BodyLength, Id
FROM posts
ORDER BY viewcount DESC
LIMIT 5;

 * sqlite:///chatdata.db
Done.

[(2270, 388566), (512, 394118), (811, 431370), (2148, 398646), (1172, 434128)]

In [153]:
# How many different locations are there in the users table?
%%sql
SELECT COUNT(DISTINCT Location) AS LocationCount
FROM users

 * sqlite:///chatdata.db
Done.

[(1900,)]

In [154]:
# What are the top 5 locations of users?
%%sql
SELECT COUNT(location), Location
FROM users
GROUP BY location
order by COUNT(location) DESC
LIMIT 5;

 * sqlite:///chatdata.db
Done.

[(117, 'Germany'),
 (100, 'India'),
 (69, 'United States'),
 (66, 'Paris, France'),
 (63, 'London, United Kingdom')]

In [155]:
# Rank the days of the week from highest to lowest in terms of the volume of ViewCount as a percentage.
%%sql
        SELECT
        CAST(strftime('%w', posts.CreationDate) AS INTEGER) AS day_of_week,
        ROUND(SUM(posts.ViewCount * 100.0) / (SELECT SUM(ViewCount) FROM posts), 2) AS view_percentage
    FROM posts
    GROUP BY day_of_week
ORDER BY view_percentage DESC;

 * sqlite:///chatdata.db
Done.

[(4, 16.82),
 (3, 16.77),
 (2, 16.26),
 (1, 15.81),
 (5, 13.56),
 (0, 11.9),
 (6, 8.89)]

# Task 3: Cross Table Queries

## Lifecycle Stage: Analyze
Let's continue the analysis with our multi-table queries.

### Cross Table Queries

From the Template SQL Queries there are a series of queries requested. You are responsible for coding the result. Use the pattern above to accomplish the coding objective.  Copy and paste the question (column B Action) into a markdown cell and answer the query. Use the pattern that you have been using above.

<div style="background-color:lemonchiffon; border:1px solid; padding:5px; margin:5px; font-weight:bold"><font color="crimson">
TODO: Enter your code below.  Just keep on inserting cells as you need them.
    </font></div>

In [156]:
# How many posts have been created by a user that has a filled out the "AboutMe" section?
%%sql
SELECT COUNT(users.id)
FROM users
INNER JOIN posts
ON users.id = posts.OwnerUserID
where AboutMe !=''

 * sqlite:///chatdata.db
Done.

[(17189,)]

In [157]:
# Considering only the users with an "AboutMe," how many posts are there per user?
%%sql
SELECT CAST(COUNT(users.id)AS float)/ (SELECT COUNT(users.id) FROM users where AboutMe !='')
FROM users
INNER JOIN posts
ON users.id = posts.OwnerUserID
where AboutMe !=''

 * sqlite:///chatdata.db
Done.

[(4.274807261875155,)]

In [158]:
# Not taking into account the commentcount field in the table posts, what are the Top 10 posts in terms of number of comments?
%%sql
SELECT posts.id as PostID, posts.title as PostTitle, COUNT(comments.id) as CommentCount
FROM posts
LEFT JOIN comments ON posts.id = comments.postId
GROUP BY posts.id, posts.title
ORDER BY CommentCount DESC
LIMIT 10;

 * sqlite:///chatdata.db
Done.

[(386853, None, 66),
 (386556, 'Strategies for predicting 100 binary choices given the previous 100', 34),
 (395232, None, 31),
 (418910, None, 31),
 (402987, 'Evaluating Unbalanced Multiclass Classifiers: Which Tests to Use?', 27),
 (386075, 'Avoiding social discrimination in model building', 26),
 (394118, 'Why do neural networks need so many training examples to perform?', 24),
 (398828, None, 23),
 (402950, 'Poisson Regression in R with individual fixed-effects and month/year fixed-effects', 23),
 (396111, 'How do I intepret these t-SNE results?', 22)]

In [159]:
# What are the Top 10 posts which have the highest cummulative (post score + comment score) score?
%%sql
SELECT posts.id as PostID, posts.title as PostTitle, SUM(comments.score) + posts.score as Score
FROM posts
LEFT JOIN comments ON posts.id = comments.postId
GROUP BY posts.id, posts.title
ORDER BY Score DESC
LIMIT 10;

 * sqlite:///chatdata.db
Done.

[(394118, 'Why do neural networks need so many training examples to perform?', 306),
 (394128, None, 169),
 (388578, None, 141),
 (398653, None, 111),
 (388566, 'Is it wrong to rephrase "1 in 80 deaths is caused by a car accident" as "1 in 80 people die as a result of a car accident?"', 101),
 (398646, 'What does "Scientists rise up against statistical significance" mean? (Comment in Nature)', 99),
 (421677, None, 96),
 (420526, None, 92),
 (400317, None, 72),
 (388582, None, 69)]

In [160]:
# Who are the top 10 users who comment the most?
%%sql
SELECT users.id as UserID, COUNT(comments.id) as NumberOfComments,
    users.reputation as UserReputation
FROM users
LEFT JOIN comments ON users.id = comments.UserId
GROUP BY users.id, users.reputation
ORDER BY reputation DESC
LIMIT 10;

 * sqlite:///chatdata.db
Done.

[(805, 1153, 228662),
 (919, 3301, 223056),
 (7290, 370, 115531),
 (686, 349, 85077),
 (28666, 158, 75024),
 (35989, 470, 71548),
 (7224, 424, 65999),
 (4253, 255, 59952),
 (1352, 422, 59160),
 (22311, 467, 51155)]

In [161]:
# Who are the top 10 users who comment the most? Done second time because ordering was strange
%%sql
SELECT
    users.id as UserID,
    COUNT(comments.id) as NumberOfComments,
    users.reputation as UserReputation
FROM users
LEFT JOIN comments ON users.id = comments.UserId
GROUP BY users.id, users.reputation
ORDER BY NumberOfComments DESC
LIMIT 10;

 * sqlite:///chatdata.db
Done.

[(919, 3301, 223056),
 (805, 1153, 228662),
 (143489, 1024, 2890),
 (11887, 805, 39200),
 (85665, 691, 17391),
 (164061, 540, 13485),
 (22047, 536, 41385),
 (158565, 504, 6482),
 (7962, 492, 8030),
 (35989, 470, 71548)]

In [162]:
# Who are the top 10 users who post the most?
%%sql
SELECT users.id as UserID, COUNT(OwnerUserId) as NumberOfPosts,
    users.reputation as UserReputation
FROM users
LEFT JOIN posts ON users.id = posts.OwnerUserId
GROUP BY users.id, users.reputation
ORDER BY reputation DESC
LIMIT 10;

 * sqlite:///chatdata.db
Done.

[(805, 230, 228662),
 (919, 203, 223056),
 (7290, 35, 115531),
 (686, 386, 85077),
 (28666, 8, 75024),
 (35989, 230, 71548),
 (7224, 233, 65999),
 (4253, 71, 59952),
 (1352, 285, 59160),
 (22311, 140, 51155)]

# Task 4: Check the Queries Table

Now let's tidy up and check the queries table.

First let's check it's contents:

In [163]:
%sql SELECT * FROM queries

 * sqlite:///chatdata.db
Done.

[('Single Table Queries', 'Which 5 users have viewed the most times and what is the sum of those views per user?', '\nSELECT Id, SUM(Views) AS TotalViews\n    FROM Users\n        GROUP BY Id\n            ORDER BY TotalViews DESC\n                LIMIT 5\n                '),
 ('Task 1', 'Create table comments', '\n    CREATE TABLE "comments" (\n    "Id" INTEGER,\n    "PostId" INTEGER,\n    "Score" INTEGER,\n    "Text" TEXT,\n    "CreationDate" TEXT,\n    "UserId" INTEGER\n    )\n    '),
 ('Task 1', 'Create table posts', '\n    CREATE TABLE "posts" (\n    "Id" INTEGER,\n"PostTypeId" INTEGER,\n"AcceptedAnswerId" INTEGER,\n"ParentId" INTEGER,\n"CreationDate" TEXT,\n"Scor ... (216 characters truncated) ... EXT,\n"Tags" TEXT,\n"AnswerCount" INTEGER,\n"CommentCount" INTEGER,\n"FavoriteCount" INTEGER,\n"ClosedDate" TEXT,\n"CommunityOwnedDate" TEXT\n)\n    '),
 ('Task 1', 'Create table users', '\nCREATE TABLE "users" (\n"Id" INTEGER,\n"Reputation" INTEGER,\n"CreationDate" TEXT,\n"DisplayName" TEXT,\n"LastAccessDate" TEXT,\n"WebsiteUrl" TEXT,\n"Location" TEXT,\n"AboutMe" TEXT,\n"Views" INTEGER,\n"UpVotes" INTEGER,\n"DownVotes" INTEGER,\n"ProfileImageUrl" TEXT,\n"AccountId" INTEGER\n)\n ')]

## Drop Duplicates

You likely have some duplicates. Lets drop them.

In [164]:
# Read the queries table into pandas
queries.drop_duplicates(inplace=True)
print(queries)

                   task                                             action  \
0  Single Table Queries  Which 5 users have viewed the most times and w...

                                               query
0  \nSELECT Id, SUM(Views) AS TotalViews\n    FRO...

In [165]:
# Read the queries table into pandas
sql = 'SELECT * FROM queries'


# Drop duplicates
queries.drop_duplicates(inplace = True) # drop duplicates

In [166]:
# Read the queries table into pandas
sql = 'SELECT * FROM queries'
queries = pd.read_sql(sql, con)

# Drop duplicates
queries.drop_duplicates(inplace = True) # drop duplicates

## Case Issues

Remember, SQL is case insensitive. Pandas IS case sensitive. Lets deal with this now by making all of the text uppercase.

In [167]:
for col in queries.columns:
    queries[col] = queries[col].str.upper()

queries

,task,action,query
0,SINGLE TABLE QUERIES,WHICH 5 USERS HAVE VIEWED THE MOST TIMES AND W...,"\nSELECT ID, SUM(VIEWS) AS TOTALVIEWS\n FRO..."
1,TASK 1,CREATE TABLE COMMENTS,"\n CREATE TABLE ""COMMENTS"" (\n ""ID"" INTE..."
2,TASK 1,CREATE TABLE POSTS,"\n CREATE TABLE ""POSTS"" (\n ""ID"" INTEGER..."
3,TASK 1,CREATE TABLE USERS,"\nCREATE TABLE ""USERS"" (\n""ID"" INTEGER,\n""REPU..."

In [168]:
# Write the now deduped uppercase dataframe back to sqlite and replace the table
queries.to_sql('queries', con, if_exists='replace', index=False)

4

## Use Case

Now that we have this queries table, lets give you some ideas about how you would use it.

Suppose you wanted to find all of the queries where you did a GROUP BY:

In [169]:
%%sql
SELECT query
    FROM queries
        WHERE query LIKE '%GROUP BY%'

 * sqlite:///chatdata.db
Done.

[('\nSELECT ID, SUM(VIEWS) AS TOTALVIEWS\n    FROM USERS\n        GROUP BY ID\n            ORDER BY TOTALVIEWS DESC\n                LIMIT 5\n                ',)]

## Now Your Turn
Find the queries that have 'DISTINCT' in them. You can do it with the %sql command or with Pandas and sql.

<div style="background-color:lemonchiffon; border:1px solid; padding:5px; margin:5px; font-weight:bold"><font color="crimson">
TODO: Complete the following code cell
    </font></div>

In [170]:
%%sql
SELECT query
    FROM queries
        WHERE query LIKE '%DISTINCT%'

 * sqlite:///chatdata.db
Done.

[]

# Close SQLite

It is good practise to close all relational databases as soon as you are finished updating them.

In [171]:
con.close()

# All Done!

Great job. You now have a good idea for how to use sql and pandas with sql. You can create your own databases from csv files and you can do extensive querying using sql. These are valuable skills that will take you a long ways in todays technological world.